msm: mdss: fix header include guard
Fixes:
In file included from
drivers/video/fbdev/msm/../../msm/mdss/mdss_hdmi_hdcp.c:21:
./include/uapi/video/msm_hdmi_hdcp_mgr.h:1:9: error:
'_UAPI__HDMI_HDCP_MGR_H' is used as a header guard
      here, followed by #define of a different macro
[-Werror,-Wheader-guard]
 #ifndef _UAPI__HDMI_HDCP_MGR_H
         ^~~~~~~~~~~~~~~~~~~~~~
./include/uapi/video/msm_hdmi_hdcp_mgr.h:2:9: note:
'_UAPI__MSM_HDMI_HDCP_MGR_H' is defined here; did you
      mean '_UAPI__HDMI_HDCP_MGR_H'?
 #define _UAPI__MSM_HDMI_HDCP_MGR_H
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
         _UAPI__HDMI_HDCP_MGR_H

Bug: 32909249
Change-Id: Id27bf6eb9120f78d741f16cdbb148e7e45a21dfe